### PR TITLE
Check controls click event

### PR DESCRIPTION
**Pull request by fznhq**
Make sure only register click event when control is showing

### CODE REVIEW

**Comment by fznhq** [comment]
So yeah I'm thinking about not allowing the event to be registered if controls are disabled, but I see the problem with my solution when updating options control later, it's not registering the event, what your thought @6c65726f79?

**Comment by 6c65726f79** [comment]
I use the `pointer-events: none` CSS property when a control button is disabled. So it prevents calling the click event, and it allows to modify the `minimizable` `maximizable` and `closeable` options later without having to set the event methods again.

I don't think there is any need to update the code, unless you have noticed a malfunction.

**Comment by fznhq** [comment]
yeah,  but should it be no event at all? something like `document .click()` can trigger the event

**Comment by 6c65726f79** [comment]
A click method can't be called manually if the console is disabled, unless there's a XSS vulnerability in the app. So it's not really a big deal, I'll leave it at that for now. But thank you anyway for your help!

**Comment by fznhq** [comment]
Thanks for the response, I'll close this pull request

**Pull request closed without merging**
